import type { FC } from "react";
import { Link } from "../renderer/Link";
import { Box } from "../theme/Box";

const DocsPage: FC = () => (
    <main>
        TODO sorry, in the meantime there is
        <Box
            as={Link}
            href="https://paka.dev/npm/@box-extractor/core"
            rel="external"
            target="_blank"
            ml="0.5"
            px="2"
            py="1"
            borderRadius="md"
            // _hover={{ backgroundColor: "bg-darker" }}
        >
            this autogenerated documentation
        </Box>
    </main>
);

export default DocsPage;
